**NUMPY**


**Numerical Python (Sayısal Python):** Numerik işlemlerde yetersiz kalındığında kullanılan matematik kütüphanesidir.

* Numpy arry lerden 50 kat daha hızlıdır.

* pip install numpy -> kurulum için

* import numpy -> çalıştırmak için

In [1]:
import numpy as np

**numpy ndarray nesnesi:** Dizilerde çalışmak için kullanırız.

In [2]:
nd = np.array([1,2,3,4,5,6,7,8,9])

print(nd)

[1 2 3 4 5 6 7 8 9]


In [4]:
print(type(nd))

<class 'numpy.ndarray'>


In [5]:
#Tuple şeklinde de kullanabiliriz.

nd = np.array({1,2,3,4,5,6,7,8,9})

print(nd)

{1, 2, 3, 4, 5, 6, 7, 8, 9}


Dizilerde Boyutlar

In [6]:
# 0 - Boyut
nd = np.array(35)
print(nd)

35


In [7]:
# 1 - Boyut
nd = np.array([1,2,3])
print(nd)

[1 2 3]


In [8]:
# 2 - Boyut
nd_2 = np.array([[1,2,3], [4,5,6]])
print(nd_2)

[[1 2 3]
 [4 5 6]]


In [9]:
# 3 - Boyut
nd_3 = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])
print(nd_3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [11]:
#Dizinin boyutunu alma -> ndim
print(nd_3.ndim)
print(nd_2.ndim)

3
2


In [12]:
#Çok Boyutlu Diziler
nd = np.array([1,2,3], ndmin=2)

print(nd)
print(nd.ndim)

[[1 2 3]]
2


In [13]:
#Dizinin satır - sütun bilgilerini alma -> shape
nd = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])

print(nd.shape)

(2, 2, 3)


In [15]:
#1 satır 10 sütundan oluştuğunu gösteriyor
nd = np.array([1,2,3,4,5,6,7,8,9,0])
print(nd.shape)

(10,)


In [16]:
#5 satır 2 sütundan oluştuğunu gösteriyor
#Dizinin satır - sütun değerlerini değiştirme -> reshape
print(nd.reshape(5,2))

[[1 2]
 [3 4]
 [5 6]
 [7 8]
 [9 0]]


In [17]:
#arange(): Sayı aralığı
nd = np.arange(0, 10, 2)
print(nd)

[0 2 4 6 8]


In [19]:
#Dizi elemanlarına erişim
nd = np.array([1,2,3,4,5])
print(nd[2]) #2. indexdeki sayıyı basar.

3


In [21]:
nd_2 = np.array([[1,2,3], [4,5,6]])
print(nd_2[1,2])
print(nd_2[0, -1])

6
3


In [22]:
nd = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])
print(nd)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [23]:
print(nd[0,1,2])

6


**Numpy Slicing**

* belirli bir indeksten belirli bir indexe kadar olan kısmı alabiliyorsun 

* başlangıç değeri ve bitiş değeri yazarak

* eğer biliş değeri verilmezse dizinin sonunu alır


In [24]:
nd = np.array([1,2,3,4,5,6,7,8])
print(nd[:4])

[1 2 3 4]


In [25]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [26]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.random.random((2, 3))

In [27]:
np.random.random((4,5))

array([[0.43531904, 0.1305814 , 0.99596098, 0.78978045, 0.87337859],
       [0.02560642, 0.18288349, 0.90970495, 0.10298344, 0.8057826 ],
       [0.71716073, 0.06405807, 0.58895039, 0.86362738, 0.28753405],
       [0.95563506, 0.84074359, 0.2435178 , 0.22836478, 0.09811705]])

In [28]:
np.linspace(4,5, num=5)

array([4.  , 4.25, 4.5 , 4.75, 5.  ])

In [30]:
np.linspace(4,5, 5, endpoint=False)

array([4. , 4.2, 4.4, 4.6, 4.8])

In [32]:
np.full((2,3),8)

array([[8, 8, 8],
       [8, 8, 8]])

In [33]:
#Matrisleri Birleştirme -> concatenate
nd1 = np.array([1,2,3])
nd2 = np.array([4,5,6])

nd3 = np.concatenate([nd1,nd2])
print(nd3)

[1 2 3 4 5 6]


In [35]:
my_lisy = [1,2,3]
nd2 = np.array([4,5,6])

nd3 = np.concatenate([nd1,nd2])
print(nd3)

[1 2 3 4 5 6]
